### ISSUE TITLE
Logblock not rolling chests back correctly

### ISSUE THREAD

**Issue by Abolduc02** [LogBlock/LogBlock#567]
I downloaded Logblock, and I was playing around with the commands to get used to them so I would know how to use them. Then I came across this. Wouldn't this command rollback the books I just took from this chest?
![2014-09-03_21 50 43](https://cloud.githubusercontent.com/assets/8682240/4177019/4c5382aa-3621-11e4-849e-d8064802e1ca.png)
When I run the command, the whole chest disappears. Any help is appreciated, thanks

**Comment by LefsFlare** [comment]
The time parameter is not supposed to accept dates. You have to limit it by actual duration like 5m, 1s, 2d etcetera.

**Comment by frymaster** [comment]
Not true.  it absolutely does accept dates

https://github.com/LogBlock/LogBlock/wiki/Params#time

However, all dates are converted implicitly into a "so many minutes before the present time" format before querying the database.  In this case I think the issue is OP was wanting more precision that the query format allows
