### ISSUE TITLE
Player names only updated if logplayerinfo is True

### ISSUE THREAD

**Issue by frymaster** [LogBlock/LogBlock#577]
LB only updates info for the player rows if logplayerinfo is set to true, but one of those things is now the name.  The logic should be changed so even if it doesn't update the *rest* of the info, it still changes the name in all situations

**Comment by frymaster** [comment]
@mibby player names in the DB should now update when a player logs in or out

**Comment by mibby** [comment]
Awesome, thanks! I had issues with logplayerinfo set to true causing the database to crawl when looking up logs. Wasn't sure if it was due to the UUID update or the additional player logging. Disabling it seems to have fixed the slow lookup for me - at least according to my staff testing. So this fix is very much appreciated. :)
