### ISSUE TITLE
SQL error on /lb sum

### ISSUE THREAD

**Issue by MarioG1** [LogBlock/LogBlock#598]
I get this error if I use /lb sum ......

http://pastebin.com/8H2Asi03

**Comment by frymaster** [comment]
Exactly what version of logblock are you using? Can you link to the download page?  I'm not getting that error on the latest version

**Comment by frymaster** [comment]
I believe the error is fixed by commit c3f5ce9a5bcd2514eb60a58baac334425dace7bc 

Since then, we've improved explosion logging, made projectile logging actually log the person who fired the projectile (arrows and such), added logging of putting fires out, massively improved the ``materials.yml`` file (you'll have to delete it to get it to be re-created), added support for extended Unicode characters in sign and chat logging, added support for worldedit 5, and increased the log insertion speed by about 6 times (on local servers; if your MySQL database is on a different machine to your minecraft server, the speed increase could be 2 or 3 hundred)

So yeah, I advise you to update :P

(of course, if this isn't the error I think it is, reopen this issue and tell me what an idiot I am)

**Comment by MarioG1** [comment]
I thin't I'm using #240 I'll update to #242 tomorrow to see if it is fixed there.

**Comment by MarioG1** [comment]
Its not fixed on build #243. Should I drop the database?

**Comment by frymaster** [comment]
I don't think it'd help.  Can you paste a pastebin of that newest build?  And is it **only** summing?

**Comment by MarioG1** [comment]
It also happens on lb sum blocks player ...

http://pastebin.com/3tHiywSd

**Comment by frymaster** [comment]
From your pastebin (important parts in bold):

>at com.mysql.jdbc.ResultSetImpl.**getString**(ResultSetImpl.java:5616) ~[spigot.jar:git-Spigot-8c3dd1f-ee6d0fa]
at de.diddiz.LogBlock.Actor.<init>(Actor.java:**49**) ~[logblock-dev.jar:?]

And if we look [here](https://github.com/LogBlock/LogBlock/blob/7e4909469928405aaaacbf5b50b03285670ea87d/src/main/java/de/diddiz/LogBlock/Actor.java#L49) we can indeed see that line 49 of ``Actor.java`` is calling the ``getString`` function

One problem: that's an old version of the file, as it exists in builds 229 and below.  In the latest source code, it's on [line 55](https://github.com/LogBlock/LogBlock/blob/e12b9eee2b9d90bf85b320b5363b44ece99822f7/src/main/java/de/diddiz/LogBlock/Actor.java#L55)

Something is going wrong with your plugin updating.  Is it possible you have two copies of the LogBlock plugin in the plugins folder?  The server would load the first one it came across and ignore the other

**Comment by MarioG1** [comment]
Found the problem there was also an logblock-dev installed on the server ^^.
