### ISSUE TITLE
name change support

### ISSUE THREAD

**Issue by seema84** [LogBlock/LogBlock#604]
After a Name change LogBlock creates a second data set. For Stats Plugins its very unfavorable. (for LogBlock too)

**Comment by frymaster** [comment]
Any version of LogBlock that's 1.90 or newer supports UUIDs

**Comment by seema84** [comment]
i use 1.94 build #250 its not closed

**Comment by frymaster** [comment]
Please paste the result of the following two SQL queries:

````sql
SELECT * FROM `lb-players` WHERE playername = "<oldname>";

SELECT * FROM `lb-players` WHERE playername = "<newname>";
````

where ``<oldname>`` and ``<newname>`` are the old and current name of a player you're seeing this happen with

**Comment by seema84** [comment]
//OLD
55 	BenniWuchert1997 	2013-12-28 16:22:52 	2015-02-08 16:12:07 	986069 	/91.37.202.239:50620 	noimport_BenniWuchert1997

//NEW
169 	TattooOnkel 	2014-06-30 18:13:59 	2014-07-27 15:14:49 	30625 	/2.163.73.207:50722 	d0ececd0-6af6-4f3d-a5d2-95603cdabb2a

So it is in all (with Name Change)

**Comment by frymaster** [comment]
This is exactly the situation described by that FAQ entry.  At the time of migration, there was no user with the name "BenniWuchert" so it couldn't put his UUID into the database, so it made one up ("noimport_BenniWuchert").  Because it made it up, it thinks "TattooOnkel" is a new player.  If the player changes their name again, it will still be tracked under the new record, because it now knows the UUID.  But the historical data from before migration will still be under the old name

**Comment by seema84** [comment]
thats not true - the player BenniWuchert has been around for over a year
this problem is at all (even in old player)

**Comment by frymaster** [comment]
Right, I've just looked things up.

The user previously known as "BenniWuchert1997" changed their name to "NachbarTotoro".  Which is what I said - because there was no minecraft user called "BenniWuchert1997" when you migrated, it could not look up that user's UUID.

Also, you'll notice I said their current name is "NachbarTotoro", not "TattooOnkel ".  I looked up "TattooOnkel" as well, and he's **never** changed his name.

So,

a) It absolutely is true, and
b) When I asked for you to give me queries for the old and current name of someone, you game me the queries for the old name of one person, and the current name of someone completely different, which wasn't helpful in any way at all.

**Comment by seema84** [comment]
oh sorry thats true .. the new form BenniWuchert  is NachbarTotoro (my fail)

**Comment by seema84** [comment]
but BenniWuchert  existed before the migration

**Comment by frymaster** [comment]
he existed before the migration, but he also **stopped** existing before it as well.  To get his UUID from the Mojang "bulk names to UUIDs" service, LogBlock would have had to ask for NachbarTotoro's UUID, but of course it didn't know that.  It would have asked for BenniWuchert and would have been told "there is currently no player by that name"

**Comment by seema84** [comment]
on my server i was the first player with uuid .. for me it should have worked (It has also not)
howsoever now i must edit it by hand?
