### ISSUE TITLE
Players in creative can create signs without them being logged

### ISSUE THREAD

**Issue by Flexo013** [LogBlock/LogBlock#615]
_Note this issue might be similar to issue #407_

Players can copy a sign with it's NBT-data and then place the sign without the creation being logged.
# Reproducing this issue
- Create a sign and write text on it and click `Done`
- Copy the sign using the pick-block hey whilst holding Ctrl (This copies the block including the NBT-data)
- Place the sign that just appeared in your inventory
- The sign you placed is not logged

**Comment by frymaster** [comment]
You're right, it's the same issue.

Currently the code ignores sign placement and just logs the sign editing packet (because ordinarily even if you make a blank sign, that packet is still sent)

I think the solution is to record sign placement separately (checking if there's pre-set text like in this bug) and then a second row for sign editing, if required (but not creating the row if pre-existing and new text are the same)

Need to make sure rollback and redo work OK with this, though

**Comment by Flexo013** [comment]
Will this be available in the next update and when would the version in which this is fixed be released?

**Comment by frymaster** [comment]
When it's fixed there'll be a notification in this bug thread, and it'll be available for download as a [dev snapshot](http://ci.md-5.net/job/LogBlock/)

**Comment by Flexo013** [comment]
Thanks for the info :+1:

**Comment by Brokkonaut** [comment]
Fixed in https://github.com/LogBlock/LogBlock/commit/37ce2303dca53659cac7b27122d925180f04c186
