### ISSUE TITLE
LogBlock world defining is broken.

### ISSUE THREAD

**Issue by mibby** [LogBlock/LogBlock#620]
@frymaster 

LogBlock dev 256 (http://ci.md-5.net/job/LogBlock/lastSuccessfulBuild/)
Spigot 1.8.7 git-Spigot-f928e7a-994b2aa (Latest compile as of 06/23 2 AM)

Just noticed that logs are merging between worlds. For example, place a block at the coordinate 5, 64, 5 in the overworld 'world'. Then tp to the nether and go to the coordinates 5, 64, 5. The logs from placing that block in the overworld show up in the nether as nether logs - logs being present in both worlds. So it seems world separation is broken. :(

Tested with nothing but Spigot and LogBlock.

**Comment by frymaster** [comment]
Can you check your ``<worldname>.yml`` files and make sure the ``table:`` settings are set to different tables?

**Comment by mibby** [comment]
Odd, it seems the nether table reset to the default lb-world. Is there any reason why it would do that? It was perfectly fine a week ago.

**Comment by frymaster** [comment]
not offhand - it should only be touching those files if they never existed before, AND the default table name should match the world name.

I know when I had this issue (which is why I recognised the problem so fast) it was because I'd copied and pasted another world's setup (because I wanted to set the logging the same) and forgot the table name was defined there

**Comment by mibby** [comment]
Quite odd. I haven't touched the world yml files in months. As far as I'm aware, everything was working fine until recently. Only I have access to these files, they existed, and I'm pretty sure I didn't copy/paste the contents.

Anyways, thanks for the speedy reply. As long as it doesn't reset itself again, all is good. 

By the way, still looking forward to log output color overhaul. :P
