### ISSUE TITLE
Logging support for usage of doors, including trapdoors

### ISSUE THREAD

**Issue by rautamiekka** [LogBlock/LogBlock#635]
I seem to recall LB did support logging all of them in older versions, in like Mc 1.6.x.

**Comment by frymaster** [comment]
Still does

As per [the params guide](https://github.com/LogBlock/LogBlock/wiki/Params) make sure you are using ``all`` and make sure ``SWITCHINTERACT`` and ``DOORINTERACT`` are set to ``true`` in the world's yml file

![2015-07-28_20 40 05](https://cloud.githubusercontent.com/assets/426814/8941714/1955ff16-3569-11e5-9a00-0071c62c3739.png)

**Comment by rautamiekka** [comment]
Which means the default configs don't pre-enable these features anymore.

**Comment by frymaster** [comment]
>anymore

Since they were first added, they've been [false by default](https://github.com/LogBlock/LogBlock/commit/e0d599c488a19310567c4f395a0c4ddac529d077#diff-ee3ec6d262dcda73b46e7825415c76d3R104)

When logging preferences were moved to a per-world basis back in late 2011, at first *all* logging was off by default, then, when some was defaulted to true, these specific options were **still** off by default.

In any case, I'm not sure what you're trying to say is the bug here

**Comment by rautamiekka** [comment]
I can't assign labels so I couldn't make this an enhancement.

I'll check those settings. If they've been off by default and still are, then, when the new Server was made they weren't enabled (not by me) during conffing.
