### ISSUE TITLE
lb-players onlinetime not being calculated correctly

### ISSUE THREAD

**Issue by devocite** [LogBlock/LogBlock#645]
I setup a trigger on the lb-players table, to detailed log to another table.
I discovered, that each time a player moved from server to server via Bungee, the last login field was updated, but the field onlinetime was not.
What I discovered, if I play on one server for 2 hours, move to another server, spend 60 seconds there, and then logout, the onlinetime field only increased by 60 seconds!
Occasionally, when moving from server to server, a logout event would occur, but mostly only when a disconnect happens.
To demonstrate this, here is the table I created:

```
-- Database: `global_logblock`
CREATE TABLE IF NOT EXISTS `global_logblock`.`lb-players-history` (
  `index` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `display_name` varchar(32) DEFAULT NULL,
  `old_lastlogin` datetime DEFAULT NULL,
  `new_lastlogin` datetime DEFAULT NULL,
  `systime` datetime DEFAULT NULL,
  `lb_onlinetime` mediumint(8) unsigned DEFAULT NULL,
  `c_onlinetime`  mediumint(8) unsigned DEFAULT NULL,
  `lb_playtime` int(8) unsigned DEFAULT NULL,
  `calc_playtime` int(10) unsigned DEFAULT NULL,
  `cpt` time DEFAULT NULL,
  `logstate` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`index`),
  UNIQUE KEY `index` (`index`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=141 
```

and the trigger

```
-- CREATE TRIGGER `playerlogging` AFTER UPDATE ON `lb-players` FOR EACH ROW
BEGIN

    DECLARE m_systime datetime; 
    DECLARE m_lb_playtime bigint;
    DECLARE m_CPT time;
    DECLARE m_calc_playtime integer;

    -- get system date and time
    set m_systime = now();

-- select TIME_TO_SEC(timediff('2015-09-16 16:40:41', '2015-09-16 16:27:07'))
    if (new.onlinetime > old.onlinetime) then
        -- Player logged off --

        -- Calculate time played for session based on lb-players onlinetime update
        set m_lb_playtime = new.onlinetime - old.onlinetime;

        -- Calculate time played for session based on current time minus lb-players.lastlogin field value
        set m_CPT = timeDIFF(m_systime, old.lastlogin);

        -- Convert m_CPT time played to seconds to compare against m_lb_playtime
        set m_calc_playtime = TIME_TO_SEC(m_CPT);

        insert into `global_logblock`.`lb-players-history` (display_name, old_lastlogin, new_lastlogin, systime, lb_onlinetime, c_onlinetime, lb_playtime, calc_playtime, cpt, logstate) values (OLD.playername, OLD.lastlogin, NEW.lastlogin, m_systime, OLD.onlinetime, NEW.onlinetime, m_lb_playtime, m_calc_playtime, m_CPT, "logoff");
else
    if (old.lastlogin < new.lastlogin) then
        -- Player logged in --
        insert into `global_logblock`.`lb-players-history` (display_name, old_lastlogin, new_lastlogin, systime, lb_onlinetime, c_onlinetime, logstate) values (OLD.playername, OLD.lastlogin, NEW.lastlogin, m_systime, OLD.onlinetime, NEW.onlinetime, "logon");
    end if;
end if;

END
```

If I take the first login date, against the log out time the time is different, and higher
`select TIME_TO_SEC(timediff(<logout time>, <login time>))`

**Comment by frymaster** [comment]
It seems like the PlayerQuitEvent isn't fired when a player moves server.  That's OK, because LB was never designed for having two different server instances touch the same `lb-players` table anyway ;)

@md-5 - I've never used Bungee, is it possible to tell in a PlayerJoinEvent if it's a "real" login as opposed to a server transfer?  If so we could ignore the event in that case

Alternatively, is there a way to make sure the logout event fires when moving server?

**Comment by devocite** [comment]
Yes, I get that LB was designed to touch lb-players simultaneously on two (or more) server instances, but on our server it is the best solution, we've found, and it works...except for this exception.

I took a look a the Spigot Bungee Cord Plugin Development forum https://www.spigotmc.org/forums/bungeecord-plugin-development.23/ and searched for PlayerQuitEvent.
There were several posts but two in particular stood out, as having a similar problem:
https://www.spigotmc.org/threads/servers-player-join-calls-first-then-last-server-player-quit.51640/#post-575428
and
https://www.spigotmc.org/threads/bungee-help-get-server-by-name-and-get-switchserver.64409/#post-708896
*"The PlayerLoginEvent (and AsyncPlayerPreLoginEvent), on the connecting server, activates before the PlayerQuitEvent, on the disconnecting server."*

There is at least a start...

**Comment by frymaster** [comment]
>"The PlayerLoginEvent (and AsyncPlayerPreLoginEvent), on the connecting server, activates before the PlayerQuitEvent, on the disconnecting server."

That's promising, I was thinking it wasn't activating at all.

The online time adjustment query is basically "add the difference between the time when the player logged off and the current last login time to their total".  It gets the last login time from the database *at the time the query is ran*.  The new server (which has a different and possibly shorter consumer queue) is updating the last login time before the first query is ran.  Instead, we could record the login time in logblock when the player logs in, work out the difference in logblock, and make the query "add this amount of seconds to their total".  This is one of the few occasions where LB being pretty "stateless" (carrying as little data around in plugin memory instead of the database) is a bad thing.

I'm trying to think if there's any other gotchas with multiple servers accessing the same DB but it's *probably* fine as long as each world table is only being used by one server.  Ordering of chat might not match cross-server (each row may not always be an earlier time than the next row) but that's not critical.

I'm trying to think what else might be affected by two
