### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KonoromiHimaries** [LogBlock/LogBlock#666]
logs
http://hastebin.com/varilihajo.sm

**Comment by frymaster** [comment]
`Access denied for user 'username'@'localhost' (using password: YES)`

Looks like you haven't configured your MySQL settings

If that is your actual details, then the issue is the password is wrong.  One issue is that YAML strings can get awkward when dealing with some special characters - try surrounding it with ' characters (and if you have any of them in your password, double it up)
