### ISSUE TITLE
Block does not have property 'facing'

### ISSUE THREAD

**Issue by DmitryRendov** [LogBlock/LogBlock#721]
- git-Spigot-f823ac5-5cffeca (MC: 1.13.1)
- LogBlock v1.13.1-SNAPSHOT (manually compiled)

https://pastebin.com/zRMVKXBq

**Comment by Brokkonaut** [comment]
This looks like a somewhat destroyed database.

The lb_materials and lb_blockstates tables do not match the log entries. Did you modify the database by hand like partial importing a backup, clearing/deleting a table or something like that?

There is not much, the plugin can do because it cannot restore the block states any more. You should import a backup of the logs or if you do not have backups delete all logblock tables, so they can be recreated.

**Comment by DmitryRendov** [comment]
Hi @Brokkonaut, - full database cleanup (all LB tables) has solved an issue.
The reason was - adding new world into logging and selective cleaninig only part of tables (with logged data). Unf I've lost tens GBs of logs - will try to figure out what I did wrong using backups on test server.

Thank you for your help!
