### ISSUE TITLE
Could not convert lb-world

### ISSUE THREAD

**Issue by seema84** [LogBlock/LogBlock#730]
database convert dont work

[Server thread/INFO]: [LogBlock] Converting 50581137 entries in lb-world
[Server thread/INFO]: [LogBlock] Could not convert lb-world: Duplicate entry '182361' for key 'PRIMARY'

and this i get on every world (with other entrys)

i have try to fix tables with REPAIR, ANALYZE , OPTIMIZE but it dont help

**Comment by Brokkonaut** [comment]
I don't really know why you have those duplicate rows, did you start the conversion multiple times?

Build 47 should now skip those duplicates instead of cancelling the conversion so hopefully the data can be converted.

When you start the server with the new build please set the version in the plugins/LogBlock/config.yml to 1.12.0 before starting the server, so it will retry the upgrade.

**Comment by seema84** [comment]
Yes i start the conversion multiple times because the first dont work.

Now i have try the Build 47 and i get this error

Could not convert lb-world: Packet for query is too large (8088919 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.

**Comment by seema84** [comment]
"Is the max_allowed_packet problem solved?"
not really.
on my host server it does not work (and this is one of the biggest hoster in germany for gameserver). anyway i have convert on a local server without this limit.
but i lost entries and i get exceptions (https://pastebin.com/N6fyNgDs)
befor the first convert i had in lb-world "50581137" entries  and after "~50,423,373"

here some screens
before:
https://cdn.discordapp.com/attachments/390613192943861760/516394556170829839/unknown.png
after:
https://cdn.discordapp.com/attachments/390613192943861760/516392313770213386/unknown.png

the item 383 is not in lb-materials
here is something wrong

**Comment by seema84** [comment]
thanks brokkonaut
