### ISSUE TITLE
no sql connection exception 

### ISSUE THREAD

**Issue by seema84** [LogBlock/LogBlock#732]
https://pastebin.com/qn13PfxF

maybe you can catch this exception better

**Comment by JulianFRL** [comment]
Got this exact same issue, when will this be fixed as it is a bit spammy in my console

**Comment by Brokkonaut** [comment]
This exception only happens when no connection to the database could be established because the database is not reachable or the config settings are incorrect. I do not see a reason to change it, because it is important for the server owners to see and fix that.

**Comment by seema84** [comment]
yes its important so show a message but maybe not the full exception?
but yes its only cosmetic

**Comment by DmitryRendov** [comment]
I have the same issue - https://pastebin.com/vPhC4JnS
There are no visible issues on database side, just a bunch of aborted connections: eg 15.76%  (34216/217149) so I believe we are not closing connections somewhere and hit limits.
Thanks!

**Comment by Brokkonaut** [comment]
This looks like the your database closes connections after some idle time. It should not cause any issues but is just a warning sent by the connection pool

**Comment by Bobbbe** [comment]
Allo Brokkonaut :)
I also have the same thing,
is it possible to adjust the "idle time"
to not lose the connection as often?
is this achievable in mysql?

**Comment by Bobbbe** [comment]
i have this 2 when im restart the server !

**Comment by Brokkonaut** [comment]
Can you please pastebin the exception?

We have 2 different issues here:

The first one (https://github.com/LogBlock/LogBlock/issues/732#issue-385512921) is a configuration error by the user (wrong database settings in the config or misconfigured mysql server or firewall). In this case the exception stack in the log is intended and will not be changed.

The second one (https://github.com/LogBlock/LogBlock/issues/732#issuecomment-443163549) is when the connection to the database breaks because the database server closes that connection or a network problem - In this case logblock is reconnecting, so there is no real problem, but the exception is printed by the logger of the connection pool. For this I will try to find a way to avoid printing that exception.

**Comment by Bobbbe** [comment]
here :)
https://pastebin.com/UwwxxfWq

**Comment by Brokkonaut** [comment]
Ok, this is an instance of the second issue - it will not cause any problems
