### ISSUE TITLE
Could not serialize ItemStack invalid string value has occurred

### ISSUE THREAD

**Issue by andrewkm** [LogBlock/LogBlock#746]
https://pastebin.com/raw/Ttu24MXv
LogBlock build 398 via https://ci.md-5.net/job/LogBlock/
Running MC 1.13.2

**Comment by Brokkonaut** [comment]
This is basically a spigot (or java) bug, as it allows strings (for example item name, lore, book content) that contain invalid characters, that are not representable as utf8.

Because of this the item cannot be stored to the database. This will not cause any other problems for logblock, its just printing that error and continue to log everything else normally.

**Comment by andrewkm** [comment]
We’re currently running on Paper 1.13.2 build 597 (latest).

Maybe @aikar would have an idea what to do?

**Comment by Brokkonaut** [comment]
I'm not sure.. It would definitely be preferable if spigot or paper would check every string for validity before using it in internal properties, but that would be a quite complex task because of the many places where strings are used in the api and in packets sent from the client.

**Comment by aikar** [comment]
What data was it? the server does kind of validate most already.... sounds like a potential encoding error.

Do you start the server with `-Dfile.encoding=UTF-8` ? if not, try that.

**Comment by Brokkonaut** [comment]
It happens here: https://bitbucket.org/asomov/snakeyaml/src/8f6cbfc9515a2fa0da0a603964533e76ea057655/src/main/java/org/yaml/snakeyaml/representer/SafeRepresenter.java?at=default&fileviewer=file-view-default#SafeRepresenter.java-126:134 (line 132)

So I think there are half surrogate characters in the string. Maybe sent from the client or from a plugin.
