### ISSUE TITLE
Logblock stocks Serverstart since Build 140 up to latest

### ISSUE THREAD

**Issue by CloudeLecaw** [LogBlock/LogBlock#837]
We were using LogBlock_1.17.0-Build139 For our 1.17.1 Server.
We tried to updtae today to Version 1LogBlock_1.17.0-Build143.
we notices that on Startup the server tries to updating tables an seems to get to sleep, forever...

![image](https://user-images.githubusercontent.com/12080017/130411201-5e2385e8-d172-426d-ac82-3b78860ee511.png)
On the Screenshot you can see the CPU and Ram went down to 0 and latest step is Updating tables
. We waited for about 20 Minutes without any result.

We also tried it with Build 142,141 and 140 with same result.

at the moment we went back to LogBlock_1.17.0-Build139
With This Version the Server starts without any problem. So something new since let the server sleep...
May it also has to do because our Database of logblock is big and contains data from over 4 years....?

We hope you can fix this with next version LogBlock_1.17.0-Build144 or find a solution for our situation (datawipe is no option) 

![image](https://user-images.githubusercontent.com/12080017/130411303-a6df09fd-3eb6-4fda-a30c-0f749708cd64.png)

**Comment by Brokkonaut** [comment]
Thats not a bug, it is just a one time conversion of the tables (expand y range to negative y, because that can be possible since minecraft 1.17). it might take some time if you have a huge log table but after that conversion the starts are just as fast as before.

Sadly its not possible to make this faster, and there is no feedback while converting as its just a "simple" database operation:
"ALTER TABLE `" + wcfg.table + "-blocks` CHANGE `y` `y` SMALLINT(5) NOT NULL"
(you can execute that yourself on the database before updating logblock if you like so there wont be that long startup time)
