### ISSUE TITLE
Modify values after installing LogBlock

### ISSUE THREAD

**Issue by helmasaur** [LogBlock/LogBlock#841]
Hey!

I was wondering if it was possible to import data from local Minecraft worlds to get the stats of the player before the mod was  added. If not, is it possible to modify the database to set the right value without breaking the relations in the database?

(I don't want to use this mod to track all the modifications made on the server, but to keep a track of each kind of blocked mined or placed and by which player.)

Thanks!

**Comment by Brokkonaut** [comment]
LogBlock might not be the best plugin for this task, if you just need the sum of changes to the block types. it is designed to log every single block change with coordinates so that it can be restored. Because of this the logging requires quite a lot of memory and counting the block sum takes a lot of time. So I would recommend to use another plugin that better fits your goals.

**Comment by helmasaur** [comment]
Yes, I realized that while checking the database and there were lines for each modification. This is amazing but not what I am searching for. Thank you very much the explanation!
