### ISSUE TITLE
Prefixes for bedrocks players removed

### ISSUE THREAD

**Issue by Doncellup** [LogBlock/LogBlock#871]
On my server (with the Geyser and floodgate plugins to allow bedrock players to join) I can't rollback bedrock players, because they have a "." prefix. 
When I enter their nickname with a dot (screenshot 1), it disappears and so the player is not recognised (screenshot 2).

![1](https://github.com/LogBlock/LogBlock/assets/90469321/5b0c4ffb-1f6b-4ec2-b269-e325884ad43d)
![2](https://github.com/LogBlock/LogBlock/assets/90469321/84eda256-e2ad-41f0-9b52-086460c0c86a)

**Comment by Brokkonaut** [comment]
Are you using the latest dev build? I could not reproduce that issue..

**Comment by Doncellup** [comment]
Thanks for your quick reply !
I don't think so, I have to use a "classic" version of the spigot site.
Is this the latest dev build https://github.com/LogBlock/LogBlock/releases/tag/v1.12 ?

**Comment by Brokkonaut** [comment]
Oh ok, you can download the dev builds here: https://www.iani.de/jenkins/job/LogBlock/ 
but old versions are not supported, and it was fixed in 1.19.

It should be possible to manually apply that change to the old version if you want to do that, this is the relevant commit: https://github.com/LogBlock/LogBlock/commit/81457ced656c1b75e7537ee0fd1a9f7057070a11

**Comment by Doncellup** [comment]
I should already download the latest version for 1.16.5…
That would be great, yes! Do I have to decompile the jar and recompile it afterwards? What tool(s) can I do this with? I have never done that

**Comment by Brokkonaut** [comment]
I have created an updated 1.16 build: https://www.iani.de/jenkins/job/Logblock%201.16/

**Comment by Doncellup** [comment]
It works perfectly now, thank you very much!!!
